### ISSUE TITLE
feat :Slide组件 -> 定制\水印\全屏

### ISSUE THREAD

**Issue by cdswyda** [toimc-team/vue3-toimc-admin#16]
- [x]  Slide组件 -> 定制 #25 
  - [x] 颜色配置
  - [x] 图标配置
- [x]  水印 #28 
- [x]  全屏

**Comment by toimc** [comment]
水印，全屏放置在组件->功能 路由下
Slide组件放置在组件 -> 动态展示 路由下

**Comment by toimc** [comment]
全屏：https://github.com/toimc-team/vue3-toimc-admin/commit/dd23a905c6ea7e4e0a3318eda3ea7dcb24334672

**Comment by toimc** [comment]
Slide组件：https://github.com/toimc-team/vue3-toimc-admin/commit/a9c1e7aebcbc09bde0094e4fc867c97f2374090c
