### ISSUE TITLE
feat :页面 -> 详情页

### ISSUE THREAD

**Issue by Alan-z-0221** [toimc-team/vue3-toimc-admin#26]
对标vben的详情页，开发基础详情页、高级详情页

- [x] 基础详情页
- [ ] 高级详情页

**Comment by Alan-z-0221** [comment]
- [基础详情页 ]

- [ 高级详情页]

**Comment by Alan-z-0221** [comment]
- [ ] 1

**Comment by Alan-z-0221** [comment]
- [ ] 基础详情页

- [ ] 高级详情页

**Comment by toimc** [comment]
https://vvbin.cn/next/#/page-demo/desc/basic

可能会使用到基础组件 t-card, basic-table, descriptions, el-timeline

路由路径：
![image](https://user-images.githubusercontent.com/51934415/161939502-309ca085-82c7-4887-bda9-4f5b57305c0b.png)
