### ISSUE TITLE
[Conference]Thin + CLI项目动员会

### ISSUE THREAD

**Issue by toimc** [toimc-team/vue3-toimc-admin#68]
每周一碰，这周议题：

1. 如何写一篇运营文档，格式与风格；
2. 好的开源项目发现与收集，周分享计划（每周大家讨论看到的一些新技术，并分享），考虑如何集成到开源项目组中来；
3. CLI项目 -> 讨论 -> thin项目 -> 需要毛遂自荐 -> 项目管理员
4. 基础组件单元测试 ->Jest or Vitest，技术选型。

#接龙

- 群里现在处在迷茫期，不知道如何加入我们的小伙伴，@一下我
- 不知道做什么的@一下我
- 手里的事情卡了2周以上的@一下我
- 潜水超过1个月的@一下我
例 清楚自己的位置，知道做什么事请；想参与，不知道做什么事情；有事情在身上，不知道怎么动手；最近太忙了，有点小迷茫；老师带躺，我想躺平；

1. Brian 清楚自己的位置，知道做什么事情；
2. [前端]小景-上海 - coderJerryM 清楚自己的位置，知道做什么事情
3. [前端]Forest-成都-Forest-211 持续跟进文档建设，关注服务端和cli基建
4. [全栈]东东-廊坊-xudongdong40 最近有点乱套，有点迷茫。
5. [前端]青丘-深圳-valcosmos 跟随Forest小组长，持续跟进文档建设🙊
6. [前端]千城-烟台-a1597284782 最近比较忙，有点小迷茫，不清楚自己应该做什么，不知道从何入手。
7. [前端]小麦-南京-weihanling 最近加班每天很晚，可能月底才有时间写文档，项目页面太多了
8. [前端]泽龙-北京-Alanz0221 目前在解决现有issues（首页看板），最近较忙进度比较慢。完成后准备完善相关文档
9. 前端-波仔-深圳-Jakeyhb 目前在做首页图表展示相关 有点慢  但是有在动 确实最近有点多事 精力跟不太上
10. [全栈]黑兔-blackitrabbit 在预研，和学习。准备下周一开始投入开发。
11. [前端]徐壮壮-snowStopXu  近一个月项目处在交付阶段，经常加班。
12. ［前端］Jolly 成 上班太忙，空闲时间想玩玩或者看看别的东西
13. [前端]白叶 目前维护主题，准备CLI项目，写文档时间有点不够。
14. [前端]方头-woodenF useRequest扩展
15. [前端]-书生-北京-idxiu 准备瘦身项目
16. [前端]小霸王-izhangjinzhe 迷茫，想参与，但不知道从哪下手，怕自己水平不行。最近一直在学大前端课程，工作也比较忙，加班较多。
17. [前端]尚可-2019997204 知道自己要做什么,也有事情在身上,只是不知道怎么开始,觉得自己知识太短缺了,目前一直在学习vue相关知识
18. [前端]🐳 alive-whalesink 在忙公司的项目，六月份可以把部分注意力转移过来
19. [前端]小王-深圳-EchoWhw 在忙公司的项目；跟进文档的编辑
20. [前端]银骑-JujiuYey 加班很忙，不知道从哪下手，正在学习vue3和ts
21. [前端]小刘刘-peri-520 最近离职在忙着背面试题，找工作，刚刚入职需要熟悉项目
22. [前端] alive-whalesink 在忙公司的项目，六月份可以把部分注意力转移过来
23. [前端]依韵-cdswyda 在写完成组件的文档，即将完成；新组件开发刚开始。
24. [前端]-小夏-skyblue 在写公司的项目，上面催的急，不知道自己擅长干哪个模块，不知道怎么去提升自己。
25. Graham 还没有时间整理，这个周六周末梳理一下，才能做到后续每天跟进进度。平时5点下班，按道理来讲，每天是可以有2个小时左右投入的。

**Comment by xudongdong40** [comment]
技术分享两个大方向：

**Comment by xudongdong40** [comment]
技术分享两个方向：
# 1. 新技术：
1. twitter 每日js（新的轮子）
2. 最新版本的更新解读、Demo
3. start少但是涨势迅猛（暂未汉化）的git项目
# 旧（成熟）技术：
1. 知识归类解答：如 yarn和npm的区别、前端面试题分享与解析。
2. 小轮子：封装常用函数、封装axios等、n个常用的vue小技巧等。
3. 项目相关：从零搭建一个admin框架（推广项目爱用）。 
4. UC震惊部：免费！最丰富的Vue管理后台框架开源了！

**Comment by xudongdong40** [comment]
单元测试的话，建议选Jest吧。毕竟老牌，一通百通。在后端项目中也同样使用。

**Comment by Forest-211** [comment]
现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。
个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣  我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。

**Comment by toimc** [comment]
CLI项目的基本要求：

1. 有默认配置；
2. 可定制（css选项，版本，更新，组件可选择...进阶考虑：发布、测试、自动化）
3. 插件部分还可以扩展，参考项目：https://github.com/antfu/vitesse/blob/main/vite.config.ts

**Comment by coderJerryM** [comment]
> 现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。 个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣 我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。



> > 现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。 个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣 我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。
> 
> 感觉其实挺难的，目前看来不如硬性的要求做一些东西。找方向是一个很难的事。 其实感觉技术不行下手才好，可能逼一逼就学会了。
> 
> 主要是在各做各的适合，同学之间的交流很少。我觉得不如划分一下小组，一小组试着负责一部分。大家互相提点意见，去做事情。各做各的，有一种割裂感。
> 
> 目前现状主要还是存在于：项目是以老师推进为主，各个同学直接互相孤立。

技术方面因素无从下手：我觉得如果比较难的组件搞定不了，那可以先从简单的写起来，项目本身没有设下限和上限，也可以参考相关竞品源码，先踩坑才会有技术方面和思想方面的进步。
交流少：可能同学们都不太熟，平时如果工作忙的话也顾不上看群，既然老师把大家聚起来了，同学们可以抽空在群里交流交流，毕竟闭门造车也不会了解太多技术上的更新迭代，提升也慢。还是建议同学们以兴趣为主，别当做是一种负担。

**Comment by coderJerryM** [comment]
> 现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。 个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣 我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。



> > 现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。 个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣 我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。
> 
> 感觉其实挺难的，目前看来不如硬性的要求做一些东西。找方向是一个很难的事。 其实感觉技术不行下手才好，可能逼一逼就学会了。
> 
> 主要是在各做各的适合，同学之间的交流很少。我觉得不如划分一下小组，一小组试着负责一部分。大家互相提点意见，去做事情。各做各的，有一种割裂感。
> 
> 目前现状主要还是存在于：项目是以老师推进为主，各个同学直接互相孤立。

技术方面因素无从下手：我觉得如果比较难的组件搞定不了，那可以先从简单的写起来，项目本身没有设下限和上限，也可以参考相关竞品源码，先踩坑才会有技术方面和思想方面的进步。
交流少：可能同学们都不太熟，平时如果工作忙的话也顾不上看群，既然老师把大家聚起来了，同学们可以抽空在群里交流交流，毕竟闭门造车也不会了解太多技术上的更新迭代，提升也慢。还是建议同学们以兴趣为主，别当做是一种负担。

**Comment by coderJerryM** [comment]
> > 现状：有部分童鞋想做事情 ，但担心自己的技术等因素无从下手 ，而导致很难加入。 个人想法：让他们找一个自己感兴趣的内容 ，多与自己感兴趣那部分功能（模块）相关的人交流 ；比如：我对服务端和cli感兴趣 我看白叶对cli也感兴趣(接龙内容中提及)，我后续就会向他请教cli相关的内容。
> 
> 感觉其实挺难的，目前看来不如硬性的要求做一些东西。找方向是一个很难的事。 其实感觉技术不行下手才好，可能逼一逼就学会了。
> 
> 主要是在各做各的适合，同学之间的交流很少。我觉得不如划分一下小组，一小组试着负责一部分。大家互相提点意见，去做事情。各做各的，有一种割裂感。
> 
> 目前现状主要还是存在于：项目是以老师推进为主，各个同学直接互相孤立。

技术方面因素无从下手：我觉得如果比较难的组件搞定不了，那可以先从简单的写起来，项目本身没有设下限和上限，也可以参考相关竞品源码，先踩坑才会有技术方面和思想方面的进步。
交流少：可能同学们都不太熟，平时如果工作忙的话也顾不上看群，既然老师把大家聚起来了，同学们可以抽空在群里交流交流，毕竟闭门造车也不会了解太多技术上的更新迭代，提升也慢。还是建议同学们以兴趣为主，别当做是一种负担。
